- name: install mysql-server
  hosts: web
  become: yes
  vars:
    login_host: db.srikantheswar.online
  vars_prompt:
  - name: mysql_root_password
    prompt: enter the db password
    private: no
  tasks:
  - name: mysql install
    ansible.builtin.dnf:
      name: mysql-server
      state: latest

  - name: Start MySQL Service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: install python and mysql dependencies
    ansible.builtin.pip:
      name: 
      - PyMysql
      - cryptography
      executable: pip3.9 # this is python version

# check password is already set up or not
  - name: check the db connections
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{mysql_root_password}}"
      login_host: "{{login_host}}"
      filter: version
    ignore_errors: yes
    register: mysql_connection_output

  - name: print the  mysql_connection_output 
    ansible.builtin.debug:
      msg: "output: {{mysql_connection_output}}"

   - name: set the root password
     ansible.builtin.command: mysql_secure_installation --set-root-pass {{mysql_root_password}}
     when: mysql_connection_output.failed is true
    



