- name: configure the frontend 
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest
  
  - name: start the service and enabled
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: remove the default file
    ansible.builtin.file:
      path:  /usr/share/nginx/html
      state: absent
  
  - name: create the html directry
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory
  - name: download code and unzip th code
    ansible.builtin.unarchive:
      src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: copy the expense.conf
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf

  - name: restarted the service
    ansible.builtin.service:
      name: nginx
      state: restarted

